
const SUPABASE_URL = "https://cmfvxnuyfzjawuimzqwj.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZnZ4bnV5ZnpqYXd1aW16cXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY4MDMsImV4cCI6MjA2OTU2MjgwM30.YIv9JkS5RCTtYtKKMDuxaMcyLs99bJVHGDUmx6sLCjU";
const { createClient } = supabase;
const supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
document.getElementById('studentForm').addEventListener('submit', async function(e) {
  e.preventDefault();

  const studentData = {
    name: document.getElementById('name').value,
    std: document.getElementById('std').value,
    div: document.getElementById('div').value,
    roll: parseInt(document.getElementById('roll').value),
    fee: parseFloat(document.getElementById('fee').value),
  };

  const { data, error } = await supabaseClient
    .from('students')
    .insert([studentData]);

  if (error) {
    alert("Error inserting data: " + error.message);
  } else {
    alert("Student data added successfully!");
    document.getElementById('studentForm').reset();
  }
});

document.getElementById('searchForm').addEventListener('submit', async function(e) {
  e.preventDefault();

  const name = document.getElementById('searchName').value.trim();
  const roll = parseInt(document.getElementById('searchRoll').value);
  const std = document.getElementById('searchStd').value.trim();
  const div = document.getElementById('searchDiv').value;

  if (!name || !std || !div || isNaN(roll)) {
    alert("Please fill all fields properly.");
    return;
  }

  const { data, error } = await supabaseClient
    .from('students')
    .select('*')
    .eq('name', name)
    .eq('roll', roll)
    .eq('std', std)
    .eq('div', div)
    .maybeSingle();

  if (error || !data) {
    alert("Student not found or error in request.");
    console.error(error);
    return;
  }
  else{
    document.getElementById('searchForm').reset();
  }

  generateReceiptPDF(data);
});


function generateReceiptPDF(student) {
  const currentYear = new Date().getFullYear();
  const receiptNumber = `RCT-${currentYear}-${Math.floor(1000 + Math.random() * 9000)}`;

  const receiptHTML =  `  
    <div style="padding: 20px; font-family: Arial; margin: 0; box-sizing: border-box;">
      <h2 style="text-align: center; margin-bottom: 0;">PAYMENT RECEIPT</h2>
      <h3 style="text-align: center; margin-top: 5px; margin-bottom: 0;">WISDOM'S ACADEMY</h3>
      <p style="text-align: center; margin-top: 5px; margin-bottom: 10px;">B/10, BALAJI BHAVAN, BESIDE DR SHARMA DENTAL CLINIC, PIPELINE,<br>
         KAJUPADA, KURLA ANDHERI ROAD, MUMBAI 400072</p>

      <h4 style="margin-bottom: 5px;">Student Details</h4>
      <p style="margin-top: 0; margin-bottom: 10px;">Name: ${student.name}<br>
         Ad Date: ${new Date().toISOString().split("T")[0]}<br>
         Program: STD ${student.std} (2025)<br>
         Total Paid: ₹${student.fee}</p>

      <h4 style="margin-bottom: 5px;">Bank Details</h4>
      <p style="margin-top: 0; margin-bottom: 10px;">Name: VISHNU MUDLIYAR<br>
         Bank: AXIS BANK<br>
         Acc No: 915010007717734<br>
         IFSC Code: UTIB0001696<br>
         Branch: SAKINAKA</p>

      <h4 style="margin-bottom: 5px;">Payment Info</h4>
      <p style="margin-top: 0; margin-bottom: 10px;">Ref Invoice: B1/25-26/0151<br>
         Payment Mode: Online<br>
         Payment ID: ${Math.floor(Math.random() * 1000)}<br>
         Payment Date: ${new Date().toDateString()}<br>
         Receipt No: ${receiptNumber}<br>
         Amount Received: ₹${student.fee}<br>
         Received By: Huzefa Sir</p>

      <h4 style="margin-bottom: 5px;">Note</h4>
      <p style="margin-top: 0; margin-bottom: 10px;">
      <ol>
        <li>Fees once paid are not refundable/transferable in any circumstances.</li>
        <li>This receipt should be carefully preserved and must be produced on demand.</li>
        <li>This receipt is valid only if signed by Authorised Signatory.</li>
        <li>This receipt copy is generated by Vishnu Sir on ${new Date().toLocaleString()}.</li>
      </ol></p>

      <p style="margin-top: 20px; margin-bottom: 10px;">
        Student/Parent Signature _____________________<br>
        Authorised Signatory _________________________
      </p>

      <p style="text-align: center; margin-top: 20px; margin-bottom: 0;"><i>This is a System Generated Receipt.</i></p>
    </div>
  `;

  const element = document.createElement('div');
  element.innerHTML = receiptHTML;

  const opt = {
    margin:       0,
    filename:     `Receipt_${student.name}.pdf`,
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, scrollY: 0 },
    jsPDF:        { unit: 'in', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(element).save();
}
